### ISSUE TITLE
Sample State, Backend Routes, Frontend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [montejododger/Tapa-Designs#3]
# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + The author username and imageurl for a post. Basically any info that the user can't change
        + Like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by paulobocanegra** [comment]
Sample State:
Wrap the whole thing in a { }. Check for missing commas, and you can remove categories. Check Schema Issue for more detail.

**Comment by paulobocanegra** [comment]
Backend Routes:
We won't need cart, just car_items. The index of cart_items is what makes the cart. If you want to keep track of orders, that will be something to work after the 2 weeks. You have enough on your plate with these features. Similarly, we won't process payments, therefore technically, there won't be actual orders.

**Comment by paulobocanegra** [comment]
Frontend Routes:
We need backticks for both routes and components.

/product/:productId

ProductShow
  --> ReviewIndex
          --> ReviewIndexItem

**Comment by montejododger** [comment]
> Frontend Routes: We need backticks for both routes and components.
> 
> /product/:productId
> 
> ProductShow --> ReviewIndex --> ReviewIndexItem

I feel like  I did this, let me know if this isnt fixed.  Going to close the issue

**Comment by paulobocanegra** [comment]
You have:

/products/:productsId

ProductShow
ProductReview


- There won't be 1 review component at the show page. There will be a couple.
Your index, and your index items.

If you want to call it ProductReview it's cool, but it should have children components of each item.

The same applies to ProductIndex
/products

ProductsIndex
    --> Should have ProductIndexItem
